### ISSUE TITLE
Unity Plugin Running Error OP_Error: Cuda check failed (35 vs. 0): CUDA driver version is insufficient for CUDA runtime version (Windows 10)

### ISSUE THREAD

**Issue by ErikaDan91** [CMU-Perceptual-Computing-Lab/openpose_unity_plugin#27]
### Issue Summary
I'm trying to use OpenPose Unity Plugin (Unity version 2018.3.6f1), but when I run the game mode I have this error:

OP_error:
Error:
Cuda check failed (35 vs. 0): CUDA driver version is insufficient for CUDA runtime version

Coming from:
- c:\users\tz1\documents\openpose\src\openpose\gpu\cuda.cpp:op::getCudaGpuNumber():48
- c:\users\tz1\documents\openpose\src\openpose\gpu\cuda.cpp:op::cudaCheck():37
- c:\users\tz1\documents\openpose\src\openpose\gpu\cuda.cpp:op::getCudaGpuNumber():58
- c:\users\tz1\documents\openpose\src\openpose\gpu\gpu.cpp:op::getGpuNumber():27
- c:\users\tz1\documents\openpose\include\openpose\wrapper\wrapperauxiliary.hpp:op::configureThreadManager():1118
- c:\users\tz1\documents\openpose\include\openpose\wrapper\wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::exec():424
- c:\users\tz1\documents\openpose\src\openpose\unity\unitybinding.cpp:op::openpose_main():453
- [Error occurred in a destructor or in the OpenPose Unity Plugin, so no std::exception has been thrown. Returning with exit status 0]

UnityEngine.Debug:LogError(Object)
OpenPose.OPWrapper:<OPLog>m__0(String, Int32) (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:231)
OpenPose.OPBind:_OPRun()
OpenPose.OPWrapper:OPExecuteThread() (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:268)

I installed the latest OpenPose portable demo available (v. 1.4), but I read that the software version required is the 1.5.0. 

OpenPose v. 1.4 (openpose-1.4.0-win64-gpu-binaries_recommended.zip) works properly. 

Can you help me?

Thx

### Executed Command (if any)
Play mode Unity 2018.3.6

### Errors (if any)
OP_error:
Error:
Cuda check failed (35 vs. 0): CUDA driver version is insufficient for CUDA runtime version

Coming from:
- c:\users\tz1\documents\openpose\src\openpose\gpu\cuda.cpp:op::getCudaGpuNumber():48
- c:\users\tz1\documents\openpose\src\openpose\gpu\cuda.cpp:op::cudaCheck():37
- c:\users\tz1\documents\openpose\src\openpose\gpu\cuda.cpp:op::getCudaGpuNumber():58
- c:\users\tz1\documents\openpose\src\openpose\gpu\gpu.cpp:op::getGpuNumber():27
- c:\users\tz1\documents\openpose\include\openpose\wrapper\wrapperauxiliary.hpp:op::configureThreadManager():1118
- c:\users\tz1\documents\openpose\include\openpose\wrapper\wrapper.hpp:op::WrapperT<struct op::Datum,class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > >,class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<class std::shared_ptr<struct op::Datum>,class std::allocator<class std::shared_ptr<struct op::Datum> > > > > > >::exec():424
- c:\users\tz1\documents\openpose\src\openpose\unity\unitybinding.cpp:op::openpose_main():453
- [Error occurred in a destructor or in the OpenPose Unity Plugin, so no std::exception has been thrown. Returning with exit status 0]

UnityEngine.Debug:LogError(Object)
OpenPose.OPWrapper:<OPLog>m__0(String, Int32) (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:231)
OpenPose.OPBind:_OPRun()
OpenPose.OPWrapper:OPExecuteThread() (at Assets/OpenPose/Modules/Scripts/OPWrapper.cs:268)

### Type of Issue
You might select multiple topics, delete the rest:
- Execution error
- Help wanted
- Question

### Your System Configuration

2. **OpenPose version**: v. 1.4.0
     OpenPose Unity Plugin default

3. **General configuration**:
    - **Operating system** : Windows 10
    - **Compiler**:  VS2017 community

4. **Non-default settings**:
    - Any custom OpenPose configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **OpenCV version**: OpenPose default (only Windows); 

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 10.0
    - **cuDNN version**: 7.5.0
    - **GPU model** (`nvidia-smi` in Ubuntu): Nvidia GeForce GTX 1070

8. If **Windows** system:
    - Default OpenPose DLL

**Comment by gineshidalgo99** [comment]
What are your Nvidia drivers version? This usually happens when those are too old.

**Comment by ErikaDan91** [comment]
Thx!! I have upgraded Nvidia drivers to version 430.39. I had the previous version. Now it works. 
Bye

**Comment by anthnyprschka** [comment]
@ErikaDan91 How did you upgrade your Nvidia drivers to version 430.39? For me it only shows 430.26 (ubuntu 16.04)

**Comment by ErikaDan91** [comment]
Hi, I upgraded my Nvidia drivers for Windows 10, and for GPU Nvidia GeForce GTX 1070 from https://www.geforce.com/drivers.

**Comment by yoonji-nam** [comment]
Same error occurred. Even if I have already upgraded driver.. Is this the only issue related with the driver? My environment is like: Windows 10, GeForce GTX1080.

**Comment by thunderknight176** [comment]
I have the same error, but I don't have GPU and when i try to turn it to CPU only it doesn't work. What do I do to remove the error if I don't have GPU?
